# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17RDOIYMjKyERrNH0Rsdctsw3iYO9Xd3k
"""

import numpy as np
import sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()

type(iris)

iris.keys()

iris['data']

iris['target_names']

iris['target']

iris['feature_names']

X_train, X_test, y_train, y_test = train_test_split(iris['data'],iris['target'])

X_train.shape

y_train.shape

X_test.shape

y_test.shape

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)

knn.score(X_test, y_test)

knn.predict([[1.2, 3.4, 5.6, 1.1]])

iris.target_names